version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: fCrMobn
       MYSQL_DATABASE: frontconference.freshjobs_db
       MYSQL_USER: admax
       MYSQL_PASSWORD: fCrMobn

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: admax
       WORDPRESS_DB_PASSWORD: fCrMobn
       WORDPRESS_DB_NAME: frontconference.freshjobs_db
volumes:
    db_data: {}